### ISSUE TITLE
Sposób zapisu i odczytu tabeli

### ISSUE THREAD

**Issue by stanislaw-zakrzewski** [stanislaw-zakrzewski/Kryptografia_1#1]
Bezpośrednio w kodzie, czy w osobnych plikach tekstowych, a może coś innego?

**Comment by MaciejSocha** [comment]
Aktualnie wydaje mi się, że najlepiej w kodzie. Jak przy robieniu tego wyjdzie, że to nie ma sensu to zmienimy.
